### ISSUE TITLE
Path issues

### ISSUE THREAD

**Issue by morloderex** [marktopper/.setup#1]
Hey Mark :)

If i do like this:
1. cd into $HOME/.setup 
2. type sh ./Install.sh hit enter

I'll get `./System/Global.sh: line 9: ./System/Install/Homestead.sh: No such file or directory` error

Can you support running the Install.sh inside the `.setup` folder instead of type the full path to it?

Hint: You can use the command pwd to determin the current path..

**Comment by marktopper** [comment]
The problem is that `pwd` will get the path where the user is running the command `sh Install.sh` and not the path for the file `Install.sh`.

This means using `pwd` as the path will result in it working when running it from the `~/.setup`-path.
But will try to get ex. Homestead at `~/System/Install/Homestead.sh` instead of `~/.setup/System/Install/Homestead.sh` when ranned from `~/`.

However, I have in the latest commit set that the path should always be `~/.setup`, so now you can run it from everywhere.
